---
title: Session 2
author: R package build
date: '2023-09-26'
slug: session2
categories: []
tags: []
---


```{r setup, include = FALSE, warning = FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  fig.height=4, 
  fig.width=6, 
  warning=FALSE, 
  message = FALSE,
  dev = "png", 
  dev.args = list(type = "cairo-png"))

library(tidyverse)
library(kableExtra)

options(kableExtra.html.bsTable = TRUE)

theme_set(theme_minimal() + 
            theme(plot.title = element_text(hjust = 0.5)))

celeste <- "#5e81ac"

```


```{r}
xaringanExtra::embed_xaringan(
  url = "https://r4ds-sports-session2.netlify.app/"
)
```


## Lab 2

Download [this dataset](./rushing.rds). It has rushing stats from the 2019 NFL regular season.

### Your job:

- Create a new data frame with the rushing stats _only for the Quarterbacks_.
- Create a new `data.frame` with a new column, `rush_attempts_per_game`. Use the formula `rush_att/games_played`.
- Create a new `data.frame` with only the following columns: `name`, `team`, and `rush_attempts_per_game`.


<!-- Download [this R data file](./nba.rds) and create a plot to understand the relationship between assits and turnovers in the 82 games of the 2017/2018 regular season. -->


<!-- ### Your job: -->

<!-- 1) Think about the data object. What kind of object if is? Use `glimpse` to find out how many variables and observations the object contains. -->

<!-- 2) Think about the aesthetic mappings you want to create. How would you show how the `Playoff` variable affects that relationship? -->

<!-- 3) Think about the geoms you are going to use to represent your data. -->

<!-- 4) Create the same plot to understand the relationship between made 2-pointers and made 3-pointers. -->

